apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service # 서비스 이름 지정
  labels:
    run: my-nginx
spec:
  ports:
  - port: 80
    nodePort: 30083
    protocol: TCP
    targetPort: 80
  selector:
    run: my-nginx
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: ghcr.io/imdb-to-kubernet/image:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80


